#region Date: Tuesday, February 03, 2015
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Controls.Button;
using Controls.Container;
using Controls.Editors.DateSelector;
using Controls.Editors.Selector;
using Controls.Grid;
using Controls.Grid.Filter;
using Controls.Grid.Upload;
using Controls.Input;
using Controls.PxControlCollection;
using Controls.ToolBarButton;
using Core.Core.Browser;
using System;


namespace Core {
    
    
    public class VX301000_ToolManagement : BaseWrapper {
        
        public PxToolBar ToolBar {get;set;} //;
        
        private c_tools_form tools_form;
        
        private c_firstselect_formactions firstselect_formactions;
        
        private c_vieweleminfo_formeleminfo vieweleminfo_formeleminfo;
        
        private c_filterworkingproject_formnewproject filterworkingproject_formnewproject;
        
        private c_filterworkingproject_formselectproject filterworkingproject_formselectproject;
        
        private c_rentals_lv0 rentals_lv0;
        
        private c_rentals_grid rentals_grid;
        
		public virtual void ClearFilter ()
		{
			ToolBar.ClearFilter.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Note ()
		{
			ToolBar.Note.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void FilesMenuShow ()
		{
			ToolBar.FilesMenuShow.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Custom ()
		{
			ToolBar.Custom.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void SelectProject ()
		{
			ToolBar.SelectProject.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void InspectelementCtrlAtlClick ()
		{
			ToolBar.InspectelementCtrlAtlClick.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void EditProject ()
		{
			ToolBar.EditProject.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ManageCustomizations ()
		{
			ToolBar.ManageCustomizations.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ActionNavigateAspx ()
		{
			ToolBar.ActionNavigateAspx.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ActionCreateNewProject ()
		{
			ToolBar.ActionCreateNewProject.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuLayoutEditor ()
		{
			ToolBar.MenuLayoutEditor.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuEditProj ()
		{
			ToolBar.MenuEditProj.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuDacEditor ()
		{
			ToolBar.MenuDacEditor.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuGraphEditor ()
		{
			ToolBar.MenuGraphEditor.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuLayoutSrc ()
		{
			ToolBar.MenuLayoutSrc.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuGraphSrc ()
		{
			ToolBar.MenuGraphSrc.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuDacSrc ()
		{
			ToolBar.MenuDacSrc.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuLayoutVS ()
		{
			ToolBar.MenuLayoutVS.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuDacVS ()
		{
			ToolBar.MenuDacVS.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void MenuGraphVS ()
		{
			ToolBar.MenuGraphVS.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ActionSelectWorkingProject ()
		{
			ToolBar.ActionSelectWorkingProject.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void LongRun ()
		{
			ToolBar.LongRun.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ElapsedTime ()
		{
			ToolBar.ElapsedTime.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Save()
		{
			if(ToolBar.Save.IsEnabled())
			{
				ToolBar.Save.ClickAndWait();
				Browser.TraceErrors();
				if (Browser.GetBrowser().Alert != null)
				{
 					throw new Exception("ALERT: " + Browser.GetBrowser().Alert.Message); 
				}
			}
		}
		public virtual void Cancel ()
		{
			ToolBar.Cancel.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Insert ()
		{
			ToolBar.Insert.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Clipboard ()
		{
			ToolBar.Clipboard.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Delete ()
		{
			ToolBar.Delete.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void First ()
		{
			ToolBar.First.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Previous ()
		{
			ToolBar.Previous.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Next ()
		{
			ToolBar.Next.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void Last ()
		{
			ToolBar.Last.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void LongRun2 ()
		{
			ToolBar.LongRun2.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void ElapsedTime2 ()
		{
			ToolBar.ElapsedTime2.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void CopyDocument ()
		{
			ToolBar.CopyDocument.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void PasteDocument ()
		{
			ToolBar.PasteDocument.ClickAndWait();
			Browser.TraceErrors();
		}
		public virtual void SaveTemplate ()
		{
			ToolBar.SaveTemplate.ClickAndWait();
			Browser.TraceErrors();
		}
        
        public VX301000_ToolManagement() {
            ScreenId = "VX301000";
            ScreenUrl = "/Pages/VX/VX301000.aspx";
            ToolBar = new PxToolBar();
            tools_form = new c_tools_form("ctl00_phF_form", "Tools_form", null, null, "VX301000");
            firstselect_formactions = new c_firstselect_formactions("ctl00_usrCaption_CustomizationDialogs_PXSmartPanel1_FormActions", "FirstSelect_FormActions", null, null, "VX301000");
            vieweleminfo_formeleminfo = new c_vieweleminfo_formeleminfo("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", "ViewElemInfo_FormElemInfo", null, null, "VX301000");
            filterworkingproject_formnewproject = new c_filterworkingproject_formnewproject("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject", "FilterWorkingProject_FormNewProject", null, null, "VX301000");
            filterworkingproject_formselectproject = new c_filterworkingproject_formselectproject("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject", "FilterWorkingProject_FormSelectProject", null, null, "VX301000");
            rentals_lv0 = new c_rentals_lv0("ctl00_phG_grid_lv0", "Rentals_lv0", null, null, "VX301000");
            rentals_grid = new c_rentals_grid(c_rentals_grid.GridLocator, c_rentals_grid.GridName);
        }
        
        protected virtual c_tools_form Tools_form {
            get {
                return tools_form;
            }
            set {
                tools_form = value;
            }
        }
        
        protected virtual c_firstselect_formactions FirstSelect_FormActions {
            get {
                return firstselect_formactions;
            }
            set {
                firstselect_formactions = value;
            }
        }
        
        protected virtual c_vieweleminfo_formeleminfo ViewElemInfo_FormElemInfo {
            get {
                return vieweleminfo_formeleminfo;
            }
            set {
                vieweleminfo_formeleminfo = value;
            }
        }
        
        protected virtual c_filterworkingproject_formnewproject FilterWorkingProject_FormNewProject {
            get {
                return filterworkingproject_formnewproject;
            }
            set {
                filterworkingproject_formnewproject = value;
            }
        }
        
        protected virtual c_filterworkingproject_formselectproject FilterWorkingProject_FormSelectProject {
            get {
                return filterworkingproject_formselectproject;
            }
            set {
                filterworkingproject_formselectproject = value;
            }
        }
        
        protected virtual c_rentals_lv0 Rentals_lv0 {
            get {
                return rentals_lv0;
            }
            set {
                rentals_lv0 = value;
            }
        }
        
        protected virtual c_rentals_grid Rentals_grid {
            get {
                return rentals_grid;
            }
            set {
                rentals_grid = value;
            }
        }
        
        public class PxToolBar : PxControlCollection {
            
			public ToolBarButton ClearFilter {get;private set;}
			public ToolBarButton Note {get;private set;}
			public ToolBarButton FilesMenuShow {get;private set;}
			public ToolBarButton Custom {get;private set;}
			public ToolBarButton SelectProject {get;private set;}
			public ToolBarButton InspectelementCtrlAtlClick {get;private set;}
			public ToolBarButton EditProject {get;private set;}
			public ToolBarButton ManageCustomizations {get;private set;}
			public ToolBarButton ActionNavigateAspx {get;private set;}
			public ToolBarButton ActionCreateNewProject {get;private set;}
			public ToolBarButton MenuLayoutEditor {get;private set;}
			public ToolBarButton MenuEditProj {get;private set;}
			public ToolBarButton MenuDacEditor {get;private set;}
			public ToolBarButton MenuGraphEditor {get;private set;}
			public ToolBarButton MenuLayoutSrc {get;private set;}
			public ToolBarButton MenuGraphSrc {get;private set;}
			public ToolBarButton MenuDacSrc {get;private set;}
			public ToolBarButton MenuLayoutVS {get;private set;}
			public ToolBarButton MenuDacVS {get;private set;}
			public ToolBarButton MenuGraphVS {get;private set;}
			public ToolBarButton ActionSelectWorkingProject {get;private set;}
			public ToolBarButton LongRun {get;private set;}
			public ToolBarButton ElapsedTime {get;private set;}
			public ToolBarButton Save {get;private set;}
			public ToolBarButton Cancel {get;private set;}
			public ToolBarButton Insert {get;private set;}
			public ToolBarButton Clipboard {get;private set;}
			public ToolBarButton Delete {get;private set;}
			public ToolBarButton First {get;private set;}
			public ToolBarButton Previous {get;private set;}
			public ToolBarButton Next {get;private set;}
			public ToolBarButton Last {get;private set;}
			public ToolBarButton LongRun2 {get;private set;}
			public ToolBarButton ElapsedTime2 {get;private set;}
			public ToolBarButton CopyDocument {get;private set;}
			public ToolBarButton PasteDocument {get;private set;}
			public ToolBarButton SaveTemplate {get;private set;}
            
            public PxToolBar() {
                Initialize();
            }
            
            private void Initialize() {
                ClearFilter = new ToolBarButton("css=div[data-cmd='clearFilter']", "ClearFilter", "", null, "VX301000");
                Note = new ToolBarButton("css=div[data-cmd='NoteShow']", "Note", "", null, "VX301000");
                FilesMenuShow = new ToolBarButton("css=div[data-cmd='FilesMenuShow']", "FilesMenuShow", "", null, "VX301000");
                Custom = new ToolBarButton("css=div[data-cmd='Custom']", "Custom", "", null, "VX301000");
                SelectProject = new ToolBarButton("ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom_item_0", "SelectProject", "", null, "VX301000");
                InspectelementCtrlAtlClick = new ToolBarButton("ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom_item_1", "InspectelementCtrlAtlClick", "", null, "VX301000");
                EditProject = new ToolBarButton("ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom_item_2", "EditProject", "", null, "VX301000");
                ManageCustomizations = new ToolBarButton("ctl00_usrCaption_CustomizationDialogs_PXToolBar1_menuCustom_item_3", "ManageCustomizations", "", null, "VX301000");
                ActionNavigateAspx = new ToolBarButton("css=div[data-cmd='actionNavigateAspx']", "ActionNavigateAspx", "", null, "VX301000");
                ActionCreateNewProject = new ToolBarButton("css=div[data-cmd='actionCreateNewProject']", "ActionCreateNewProject", "", null, "VX301000");
                MenuLayoutEditor = new ToolBarButton("css=div[data-cmd='menuLayoutEditor']", "MenuLayoutEditor", "", null, "VX301000");
                MenuEditProj = new ToolBarButton("css=div[data-cmd='menuEditProj']", "MenuEditProj", "", null, "VX301000");
                MenuDacEditor = new ToolBarButton("css=div[data-cmd='menuDacEditor']", "MenuDacEditor", "", null, "VX301000");
                MenuGraphEditor = new ToolBarButton("css=div[data-cmd='menuGraphEditor']", "MenuGraphEditor", "", null, "VX301000");
                MenuLayoutSrc = new ToolBarButton("css=div[data-cmd='menuLayoutSrc']", "MenuLayoutSrc", "", null, "VX301000");
                MenuGraphSrc = new ToolBarButton("css=div[data-cmd='menuGraphSrc']", "MenuGraphSrc", "", null, "VX301000");
                MenuDacSrc = new ToolBarButton("css=div[data-cmd='menuDacSrc']", "MenuDacSrc", "", null, "VX301000");
                MenuLayoutVS = new ToolBarButton("css=div[data-cmd='menuLayoutVS']", "MenuLayoutVS", "", null, "VX301000");
                MenuDacVS = new ToolBarButton("css=div[data-cmd='menuDacVS']", "MenuDacVS", "", null, "VX301000");
                MenuGraphVS = new ToolBarButton("css=div[data-cmd='menuGraphVS']", "MenuGraphVS", "", null, "VX301000");
                ActionSelectWorkingProject = new ToolBarButton("css=div[data-cmd='actionSelectWorkingProject']", "ActionSelectWorkingProject", "", null, "VX301000");
                LongRun = new ToolBarButton("css=div[data-cmd='LongRun']", "LongRun", "", null, "VX301000");
                ElapsedTime = new ToolBarButton("css=div[data-cmd='ElapsedTime']", "ElapsedTime", "", null, "VX301000");
                Save = new ToolBarButton("css=div[data-cmd='Save']", "Save", "", null, "VX301000");
                Cancel = new ToolBarButton("css=div[data-cmd='Cancel']", "Cancel", "", null, "VX301000");
                Insert = new ToolBarButton("css=div[data-cmd='Insert']", "Insert", "", null, "VX301000");
                Clipboard = new ToolBarButton("css=li>div.toolsBtn[tooltip='Clipboard']", "Clipboard", "", null, "VX301000");
                Delete = new ToolBarButton("css=div[data-cmd='Delete']", "Delete", "", null, "VX301000");
                Delete.ConfirmAction = () => Browser.Confirm(true);
                First = new ToolBarButton("css=div[data-cmd='First']", "First", "", null, "VX301000");
                Previous = new ToolBarButton("css=div[data-cmd='Previous']", "Previous", "", null, "VX301000");
                Next = new ToolBarButton("css=div[data-cmd='Next']", "Next", "", null, "VX301000");
                Last = new ToolBarButton("css=div[data-cmd='Last']", "Last", "", null, "VX301000");
                LongRun2 = new ToolBarButton("css=div[data-cmd='LongRun']", "LongRun2", "", null, "VX301000");
                ElapsedTime2 = new ToolBarButton("css=div[data-cmd='ElapsedTime']", "ElapsedTime2", "", null, "VX301000");
                CopyDocument = new ToolBarButton("css=li[data-cmd='CopyPaste@CopyDocument']", "CopyDocument", "", null, "VX301000");
                PasteDocument = new ToolBarButton("css=li[data-cmd='CopyPaste@PasteDocument']", "PasteDocument", "", null, "VX301000");
                SaveTemplate = new ToolBarButton("css=li[data-cmd='CopyPaste@SaveTemplate']", "SaveTemplate", "", null, "VX301000");
            }
        }
        
        public class c_tools_form : Container {
            
			public Selector ToolCD {get;set;}
			public Input Description {get;set;}
			public Input Cost {get;set;}
			public Input SerialNumber {get;set;}
            
            public c_tools_form(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_tools_form(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            private void Initialize() {
                ToolCD = new Selector("ctl00_phF_form_edToolCD", "ToolCD", "ctl00_phF_form", null, "VX301000");
                ToolCD.DataField = "ToolCD";
                Description = new Input("ctl00_phF_form_edDescription", "Description", "ctl00_phF_form", null, "VX301000");
                Description.DataField = "Description";
                Cost = new Input("ctl00_phF_form_edCost", "Cost", "ctl00_phF_form", null, "VX301000");
                Cost.DataField = "Cost";
                SerialNumber = new Input("ctl00_phF_form_edSerialNumber", "SerialNumber", "ctl00_phF_form", null, "VX301000");
                SerialNumber.DataField = "SerialNumber";
                ContainerType = "U";
                DataMemberName = "Tools";
            }
        }
        
        public class c_firstselect_formactions : Container {
            
			public Input Key {get;set;}
            
            public c_firstselect_formactions(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_firstselect_formactions(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            private void Initialize() {
                Key = new Input("ctl00_usrCaption_CustomizationDialogs_PXSmartPanel1_FormActions_edKey", "Key", "ctl00_usrCaption_CustomizationDialogs_PXSmartPanel1_FormActions", null, "VX301000");
                Key.DataField = "Key";
                ContainerType = "U";
                DataMemberName = "FirstSelect";
            }
        }
        
        public class c_vieweleminfo_formeleminfo : Container {
            
            public PxButtonCollection Buttons {get;set;} //;
            
			public Input AspxControl {get;set;}
			public Input CacheType {get;set;}
			public Input FieldName {get;set;}
			public Input GraphName {get;set;}
            
            public c_vieweleminfo_formeleminfo(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_vieweleminfo_formeleminfo(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            public virtual void Customize() {
                ActionClick(Buttons.Customize);
            }
            
            public virtual void Actions() {
                ActionClick(Buttons.Actions);
            }
            
            public virtual void Cancel() {
                ActionClick(Buttons.Cancel);
            }
            
            private void Initialize() {
                AspxControl = new Input("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_edAspxControl", "AspxControl", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", null, "VX301000");
                AspxControl.DataField = "AspxControl";
                CacheType = new Input("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_CacheType", "CacheType", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", null, "VX301000");
                CacheType.DataField = "CacheType";
                FieldName = new Input("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_FieldName", "FieldName", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", null, "VX301000");
                FieldName.DataField = "FieldName";
                GraphName = new Input("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo_GraphName", "GraphName", "ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_FormElemInfo", null, "VX301000");
                GraphName.DataField = "GraphName";
                ContainerType = "U";
                DataMemberName = "ViewElemInfo";
                Buttons = new PxButtonCollection();
            }
            
            public class PxButtonCollection : PxControlCollection {
                
				public Button Customize {get;private set;}
				public Button Actions {get;private set;}
				public Button Cancel {get;private set;}
                
                public PxButtonCollection() {
                    Initialize();
                }
                
                private void Initialize() {
                    Customize = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_PXButton3", "", null, null, "VX301000");
                    Actions = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_ButtonGraphActions", "", null, null, "VX301000");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_PanelElemInfo_PXButton4", "", null, null, "VX301000");
                }
            }
        }
        
        public class c_filterworkingproject_formnewproject : Container {
            
            public PxButtonCollection Buttons {get;set;} //;
            
			public Input NewProject {get;set;}
            
            public c_filterworkingproject_formnewproject(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_filterworkingproject_formnewproject(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            public virtual void Ok() {
                ActionClick(Buttons.Ok);
            }
            
            public virtual void Cancel() {
                ActionClick(Buttons.Cancel);
            }
            
            private void Initialize() {
                NewProject = new Input("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject_edNewProject", "NewProject", "ctl00_usrCaption_CustomizationDialogs_DlgNewProject_FormNewProject", null, "VX301000");
                NewProject.DataField = "NewProject";
                ContainerType = "U";
                DataMemberName = "FilterWorkingProject";
                Buttons = new PxButtonCollection();
            }
            
            public class PxButtonCollection : PxControlCollection {
                
				public Button Ok {get;private set;}
				public Button Cancel {get;private set;}
                
                public PxButtonCollection() {
                    Initialize();
                }
                
                private void Initialize() {
                    Ok = new Button("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_DlgNewProjectButtonOk", "", null, null, "VX301000");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_DlgNewProject_DlgNewProjectButtonCancel", "", null, null, "VX301000");
                }
            }
        }
        
        public class c_filterworkingproject_formselectproject : Container {
            
            public PxButtonCollection Buttons {get;set;} //;
            
			public Selector Name {get;set;}
            
            public c_filterworkingproject_formselectproject(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_filterworkingproject_formselectproject(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            public virtual void Ok() {
                ActionClick(Buttons.Ok);
            }
            
            public virtual void Cancel() {
                ActionClick(Buttons.Cancel);
            }
            
            public virtual void New() {
                ActionClick(Buttons.New);
            }
            
            private void Initialize() {
                Name = new Selector("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject_edWP", "Name", "ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_FormSelectProject", null, "VX301000");
                Name.DataField = "Name";
                ContainerType = "U";
                DataMemberName = "FilterWorkingProject";
                Buttons = new PxButtonCollection();
            }
            
            public class PxButtonCollection : PxControlCollection {
                
				public Button Ok {get;private set;}
				public Button Cancel {get;private set;}
				public Button New {get;private set;}
                
                public PxButtonCollection() {
                    Initialize();
                }
                
                private void Initialize() {
                    Ok = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_SelectProjectOk", "", null, null, "VX301000");
                    Cancel = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_SelectProjectCancel", "", null, null, "VX301000");
                    New = new Button("ctl00_usrCaption_CustomizationDialogs_WizardSelectProject_BtnNewProject", "", null, null, "VX301000");
                }
            }
        }
        
        public class c_rentals_lv0 : Container {
            
			public Selector CustomerID {get;set;}
			public DateSelector StartDate {get;set;}
			public DateSelector EndDate {get;set;}
			public Selector Es {get;set;}
            
            public c_rentals_lv0(String locator, String name) : 
                    base(locator, name) {
                Initialize();
            }
            
            public c_rentals_lv0(String locator, String name, String tabid, int? index, String screenId) : 
                    base(locator, name, tabid, index, screenId) {
                Initialize();
            }
            
            private void Initialize() {
                CustomerID = new Selector("ctl00_phG_grid_lv0_edCustomerID", "CustomerID", "ctl00_phG_grid_lv0", null, "VX301000");
                CustomerID.DataField = "CustomerID";
                StartDate = new DateSelector("ctl00_phG_grid_lv0_edStartDate", "StartDate", "ctl00_phG_grid_lv0", null, "VX301000");
                StartDate.DataField = "StartDate";
                EndDate = new DateSelector("ctl00_phG_grid_lv0_edEndDate", "EndDate", "ctl00_phG_grid_lv0", null, "VX301000");
                EndDate.DataField = "EndDate";
                Es = new Selector("ctl00_phG_grid_lv0_es", "Es", "ctl00_phG_grid_lv0", null, "VX301000");
                Es.DataField = "";
                ContainerType = "U";
                DataMemberName = "Rentals";
            }
        }
        
        public class c_rentals_grid : Grid<c_rentals_grid.c_grid_row> {
            
            private static String _GridLocator = "ctl00_phG_grid";
            
            private static String _GridName = "Rentals_grid";
            
            private c_grid_filter_ex gridfilter;
            
            private c_grid_upload gridupload;
            
            public PxToolBar ToolBar {get;set;} //;
            
            public Selector ContextSearch;
            
		    public virtual void New()
		    {
			    if(ToolBar.New.IsEnabled())
			    {
				    ToolBar.New.ClickAndWait();
				    if (Browser.GetBrowser().Alert != null)
				    {
 					    throw new Exception("ALERT: " + Browser.GetBrowser().Alert.Message); 
				    }
			    }
		    }
            
            public c_rentals_grid(String locator, String name) : 
                    base(locator, name) {
                gridfilter = new c_grid_filter_ex("ctl00_phG_grid_fe_gf", null, null, null, "VX301000");
                gridupload = new c_grid_upload("ctl00_phG_grid_upldr", "Files Upload", null, null, "VX301000");
                ToolBar = new PxToolBar();
                ContextSearch = new Selector("ctl00_phG_grid_ab_tlb_fb", "ContextSearch", "ctl00_phG_grid", null, "VX301000");
                ContainerType = "U";
                DataMemberName = "Rentals";
            }
            
            public static String GridLocator {
                get {
                    return _GridLocator;
                }
                set {
                    _GridLocator = value;
                }
            }
            
            public static String GridName {
                get {
                    return _GridName;
                }
                set {
                    _GridName = value;
                }
            }
            
            public virtual c_grid_filter_ex FilterForm {
                get {
                    c_grid_filter.Lctr = _GridLocator;
                    return gridfilter;
                }
                set {
                    c_grid_filter.Lctr = _GridLocator;
                    gridfilter = value;
                }
            }
            
            public virtual c_grid_upload UploadForm {
                get {
                    return gridupload;
                }
                set {
                    gridupload = value;
                }
            }
            
            public virtual void Refresh() {
                ActionClick(ToolBar.Refresh);
            }
            
            public virtual void Delete() {
                ActionClick(ToolBar.Delete);
            }
            
            public virtual void Adjust() {
                ActionClick(ToolBar.Adjust);
            }
            
            public virtual void Export() {
                ActionClick(ToolBar.Export);
            }
            
            public virtual void FilterBar() {
                ActionClick(ToolBar.FilterBar);
            }
            
            public virtual void PageFirst() {
                ActionClick(ToolBar.PageFirst);
            }
            
            public virtual void PagePrev() {
                ActionClick(ToolBar.PagePrev);
            }
            
            public virtual void PageNext() {
                ActionClick(ToolBar.PageNext);
            }
            
            public virtual void PageLast() {
                ActionClick(ToolBar.PageLast);
            }
            
            public class c_grid_filter_ex : c_grid_filter {
                
                private c_fields fields;
                
                public c_grid_filter_ex(String locator) : 
                        base(locator) {
                    fields = new c_fields();
                }
                
                public c_grid_filter_ex(String locator, String name, String tabid, int? index, String screenId) : 
                        base(locator, name, tabid, index, screenId) {
                    fields = new c_fields();
                }
                
                public virtual c_fields Fields {
                    get {
                        return fields;
                    }
                    set {
                        fields = value;
                    }
                }
                
                public class c_fields {
                    
                    public c_rule.c_property Files;
                    
                    public c_rule.c_property Notes;
                    
                    public c_rule.c_property CustomerID;
                    
                    public c_rule.c_property StartDate;
                    
                    public c_rule.c_property EndDate;
                    
                    public c_rule.c_property RentalID;
                    
                    public c_rule.c_property ToolCD;
                    
                    public c_fields() {
                        Files = new c_rule.c_property("", "Int32", "PX.Web.UI.PXSelector", 2, "VX301000");
                        Notes = new c_rule.c_property("", "Int32", "PX.Web.UI.PXSelector", 3, "VX301000");
                        CustomerID = new c_rule.c_property("Customer", "String", "PX.Web.UI.PXSelector", 4, "VX301000");
                        StartDate = new c_rule.c_property("Start Date", "DateTime", "PX.Web.UI.PXDateTimeEdit", 5, "VX301000");
                        EndDate = new c_rule.c_property("End Date", "DateTime", "PX.Web.UI.PXDateTimeEdit", 6, "VX301000");
                        RentalID = new c_rule.c_property("RentalID", "Int32", "PX.Web.UI.PXTextEdit", 7, "VX301000");
                        ToolCD = new c_rule.c_property("Tool Code", "String", "PX.Web.UI.PXTextEdit", 8, "VX301000");
                    }
                }
            }
            
            public class PxToolBar : PxControlCollection {
                
				public ToolBarButton Refresh {get;private set;}
				public ToolBarButton New {get;private set;}
				public ToolBarButton Delete {get;private set;}
				public ToolBarButton Adjust {get;private set;}
				public ToolBarButton Export {get;private set;}
				public ToolBarButton FilterBar {get;private set;}
				public ToolBarButton PageFirst {get;private set;}
				public ToolBarButton PagePrev {get;private set;}
				public ToolBarButton PageNext {get;private set;}
				public ToolBarButton PageLast {get;private set;}
                
                public PxToolBar() {
                    Initialize();
                }
                
                private void Initialize() {
                    Refresh = new ToolBarButton("css=div[data-cmd='Refresh']", "Refresh", "ctl00_phG_grid", null, "VX301000");
                    New = new ToolBarButton("css=div[data-cmd='AddNew']", "New", "ctl00_phG_grid", null, "VX301000");
                    Delete = new ToolBarButton("css=div[data-cmd='Delete']", "Delete", "ctl00_phG_grid", null, "VX301000");
                    Adjust = new ToolBarButton("css=div[data-cmd='AdjustColumns']", "Adjust", "ctl00_phG_grid", null, "VX301000");
                    Export = new ToolBarButton("css=div[data-cmd='ExportExcel']", "Export", "ctl00_phG_grid", null, "VX301000");
                    PageFirst = new ToolBarButton("css=div[data-cmd='PageFirst']", "PageFirst", "ctl00_phG_grid", null, "VX301000");
                    PagePrev = new ToolBarButton("css=div[data-cmd='PagePrev']", "PagePrev", "ctl00_phG_grid", null, "VX301000");
                    PageNext = new ToolBarButton("css=div[data-cmd='PageNext']", "PageNext", "ctl00_phG_grid", null, "VX301000");
                    PageLast = new ToolBarButton("css=div[data-cmd='PageLast']", "PageLast", "ctl00_phG_grid", null, "VX301000");
                }
            }
            
            public class c_grid_row {
                
				public Selector Files {get;set;}
				public Selector Notes {get;set;}
				public Selector CustomerID {get;set;}
				public DateSelector StartDate {get;set;}
				public DateSelector EndDate {get;set;}
				public Input RentalID {get;set;}
				public Input ToolCD {get;set;}
                
                public c_grid_row() {
                    Files = new Selector("_ctl00_phG_grid_lv0_es", "", "ctl00_phG_grid", 2, "VX301000");
                    Files.DataField = "";
                    Files.ValueType = "PX.Web.UI.PXSelector";
                    Notes = new Selector("_ctl00_phG_grid_lv0_es", "", "ctl00_phG_grid", 3, "VX301000");
                    Notes.DataField = "";
                    Notes.ValueType = "PX.Web.UI.PXSelector";
                    CustomerID = new Selector("_ctl00_phG_grid_lv0_edCustomerID", "Customer", "ctl00_phG_grid", 4, "VX301000");
                    CustomerID.DataField = "CustomerID";
                    CustomerID.ValueType = "PX.Web.UI.PXSelector";
                    StartDate = new DateSelector("_ctl00_phG_grid_lv0_edStartDate", "Start Date", "ctl00_phG_grid", 5, "VX301000");
                    StartDate.DataField = "StartDate";
                    StartDate.ValueType = "PX.Web.UI.PXDateTimeEdit";
                    EndDate = new DateSelector("_ctl00_phG_grid_lv0_edEndDate", "End Date", "ctl00_phG_grid", 6, "VX301000");
                    EndDate.DataField = "EndDate";
                    EndDate.ValueType = "PX.Web.UI.PXDateTimeEdit";
                    RentalID = new Input("ctl00_phG_grid_en", "RentalID", "ctl00_phG_grid", 7, "VX301000");
                    RentalID.DataField = "RentalID";
                    RentalID.ValueType = "PX.Web.UI.PXTextEdit";
                    ToolCD = new Input("ctl00_phG_grid_em", "Tool Code", "ctl00_phG_grid", 8, "VX301000");
                    ToolCD.DataField = "ToolCD";
                    ToolCD.ValueType = "PX.Web.UI.PXTextEdit";
                }
            }
        }
    }
}
#endregion
